### ISSUE TITLE
Hmm this code seems familiar....

### ISSUE THREAD

**Issue by dxmxnlord** [ricksaha2000/MEDHEART#22]

**Comment by dxmxnlord** [comment]
I wonder who wrote this..

**Comment by dxmxnlord** [comment]
I mean it looks like the code of someone who almost passed out trying to finish writing it before a hackathon deadline but who knows ...

**Comment by dxmxnlord** [comment]
If it were copied the owner of this code would feel pretty mad that his hardwork and ballsweat was used by another person in a cheap attempt. Man, his life sure would suck.

**Comment by ricksaha2000** [comment]
>< who knows

**Comment by dxmxnlord** [comment]
The owner would probably ask you to take this code down or at least CREDIT himfor his work.

**Comment by ricksaha2000** [comment]
Please do acknowledge the comments with a detailed plagiarism report . I am closing this issue for now .
